### ISSUE TITLE
Theming picker

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/mw3-playground#3]
# Overview

It would be nice for the user to be able to dynamically generate a theme (i.e. generate CSS variables) via a user interface of some kind.

## Tasks

- [ ] Design a theme picker user interface
- [ ] Implement theme picker functionality
- [ ] Figure out how to programmatically determine what CSS variables are available?
- [ ] Allow for themes to be customisable on the fly
