### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/mw3-playground#4]
# Overview

The library version used should be shown in the website to indicate what version was used.

An installation guide (we could just point to the [material-web GitHub repository](https://github.com/material-components/material-web)) would be helpful as well.

## Tasks

- [ ] Show library version used
- [ ] Add steps on how to use the library
- [ ] Show what is needed to use a specific component (e.g. `import '@material/web/button/etc'`)
