### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/mw3-playground#6]
# Overview

Currently, the app uses light theme colours, which might be a bit jarring for users who prefer dark mode. We can also look for the `prefers-color-scheme: dark` media query as well.

## Tasks

- [ ] Design dark mode variant
- [ ] Add dark theme picker
- [ ] Verify that the dark theme colours don't affect the demos
